version: '3.5'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test

  bot:
    image: rawello/wikitggo-bot
    environment:
      CREATE_TABLE: "yes"
      DB_SWITCH: "on"
      TOKEN: "token"
      HOST: db
      PORT: 5432
      USER: postgres
      PASSWORD: test
      DBNAME: postgres
      SSLMODE: disable
